const star = "/Star1.png";

export default [
  {
    id: 1,
    image: "/katie-zaferes.png",
    star: star,
    rating: "5.0",
    span: "(6) USA",
    title: "Life lessons with Katie Zaferes",
    cardRate: 136,
    cardRateUnit: "/ person",
    openSpots: 0,
  },
  {
    id: 2,
    image: "/cristiano.jpg",
    star: star,
    rating: "5.0",
    span: "(5).PG",
    title: "Motivation from the GOAT",
    cardRate: 999,
    cardRateUnit: "/ person",
    openSpots: 25,
  },
  {
    id: 3,
    image: "/narcosImage.jpg",
    star: star,
    rating: "5.0",
    span: "(5).MX",
    title: "Plata or Plomo",
    cardRate: 777,
    cardRateUnit: "/ person",
    openSpots: 56,
  },
  {
    id: 4,
    image: "/katie-zaferes.png",
    star: star,
    rating: "5.0",
    span: "(6).USA",
    title: "Life lessons with Katie Zaferes",
    cardRate: 136,
    cardRateUnit: "/ person",
    openSpots: 77,
  },
  {
    id: 5,
    image: "/cristiano.jpg",
    star: star,
    rating: "5.0",
    span: "(5).PG",
    title: "Motivation from the GOAT",
    cardRate: 999,
    cardRateUnit: "/ person",
    openSpots: 23,
  },
  {
    id: 6,
    image: "/narcosImage.jpg",
    star: star,
    rating: "5.0",
    span: "(5).MX",
    title: "Plata or Plomo",
    cardRate: 777,
    cardRateUnit: "/ person",
    openSpots: 0,
  },
  {
    id: 7,
    image: "/katie-zaferes.png",
    star: star,
    rating: "5.0",
    span: "(6).USA",
    title: "Life lessons with Katie Zaferes",
    cardRate: 136,
    cardRateUnit: "/ person",
    openSpots: 0,
  },
  {
    id: 8,
    image: "/cristiano.jpg",
    star: star,
    rating: "5.0",
    span: "(5).PG",
    title: "Motivation from the GOAT",
    cardRate: 999,
    cardRateUnit: "/ person",
    openSpots: 0,
  },
  {
    id: 9,
    image: "/narcosImage.jpg",
    star: star,
    rating: "5.0",
    span: "(5).MX",
    title: "Plata or Plomo",
    cardRate: 777,
    cardRateUnit: "/ person",
    openSpots: 0,
  },
];
